### ISSUE TITLE
你这里面只有库，怎么使用的呢，能否将整个工程上传

### ISSUE THREAD

**Issue by Delay-n-days** [ErBWs/Easy-UI#1]
#define EasyUIScreenInit()                                      (ips114_init())
#define EasyUIDisplayStr(x, y, str)                             (IPS114_ShowStr(x, y, str))
#define EasyUIDisplayFloat(x, y, dat, num, pointNum)            (IPS114_ShowFloat(x, y, dat, num, pointNum))
#define EasyUIDrawDot(x, y, color)                              (IPS114_DrawPoint(x, y, color))
#define EasyUIDrawBox(x, y, width, height, color)               (IPS114_DrawBox(x, y, width, height, color))
#define EasyUIDrawFrame(x, y, width, height, color)             (IPS114_DrawFrame(x, y, width, height, color))
#define EasyUIDrawRFrame(x, y, width, height, color, r)         (IPS114_DrawRFrame(x, y, width, height, color, r))
#define EasyUIDrawRBox(x, y, width, height, color, r)           (IPS114_DrawRBox(x, y, width, height, color, r))
#define EasyUIClearBuffer()                                     (IPS114_ClearBuffer())
#define EasyUISendBuffer()                                      (IPS114_SendBuffer())
#define EasyUISetDrawColor(mode)                                (IPS114_SetDrawColor(mode))
#define EasyUIDisplayBMP(x, y, width, height, pic)              (IPS114_ShowBMP(x, y, width, height, pic))
#define EasyUIModifyColor()                                     (IPS114_ModifyColor())
没有注明这部分接口的作用，我想要移植到其他显示器该如何使用

**Comment by ErBWs** [comment]
README里面写了此部分仅部分开源，完整工程后续开源
你可以先用u8g2对应的函数移植一下
